---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Delete pmm-server container
      community.docker.docker_container:
        name: pmm-server
        state: absent

    - name: Delete pmm-data container
      community.docker.docker_container:
        name: pmm-data
        state: absent
