---
- name: Prepare
  hosts: all
  vars:
    docker_apt_signed_by: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    docker_apt_uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    docker_architecture_map:
      "x86_64": "amd64"
      "aarch64": "arm64"
      "aarch": "arm64"
      "armhf": "armhf"
      "armv7l": "armhf"

    docker_dependencies:
      - curl
      - gnupg2
      - python3-debian
      - python3-docker
    docker_packages:
      - docker-ce-cli
    docker_package_state: present

  tasks:
    - name: Install Docker dependencies
      ansible.builtin.apt:
        name: "{{ docker_dependencies }}"
        update_cache: true

    - name: Configure Docker APT repository
      ansible.builtin.deb822_repository:
        architectures: "{{ docker_architecture_map[ansible_facts['architecture']] }}"
        components: stable
        name: docker
        signed_by: "{{ docker_apt_signed_by }}"
        suites: "{{ ansible_facts['distribution_release'] }}"
        uris: "{{ docker_apt_uris }}"

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: "{{ docker_package_state }}"
        update_cache: true
