---
scenario:
  name: debian-10

platforms:
  - name: instance
    image: debian:buster
    command: /lib/systemd/systemd
    privileged: true
    env:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
